#!/usr/bin/env python3
"""Turn the PokerTH logo into characters the Plus/4 can print.

The machine has no bitmap to spare and no need of one: a character set lives
in RAM already, for the card suits, and the codes from 128 up are free the
moment the TED is told to stop inverting them. That is 128 characters of
eight by eight pixels - enough for a logo, if the tiles that repeat are only
stored once. The blank ones do not need storing at all; they are spaces.

    ./make-logo.py [size in characters]

Needs rsvg-convert and Pillow, and only when the logo changes: what it writes
is logo.h, which is what the build uses.
"""

import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SVG = HERE / "pokerth.svg"
OUT = HERE / "logo.h"
FIRST_CODE = 128        # where our own characters start
MAX_TILES = 128         # and how many there is room for


def rasterise(size_px: int):
    """The logo at the size wanted, with the empty margin taken off first.

    The drawing sits in a square with a good deal of air around it. Rendered
    straight to the target size, a third of the characters would be spent on
    nothing - so it is rendered large, cropped to what is actually drawn, and
    only then brought down to size.
    """
    from PIL import Image

    png = HERE / "build" / "logo.png"
    png.parent.mkdir(exist_ok=True)
    big = size_px * 6
    subprocess.run(["rsvg-convert", "-w", str(big), "-h", str(big),
                    "-o", str(png), str(SVG)], check=True)

    # Flatten onto black: what is not drawn is background, not white.
    source = Image.open(png).convert("RGBA")
    flat = Image.new("RGBA", source.size, (0, 0, 0, 255))
    flat.alpha_composite(source)
    grey = flat.convert("L")

    box = grey.point(lambda v: 255 if v > 24 else 0).getbbox()
    if box:
        grey = grey.crop(box)
    return grey.resize((size_px, size_px), Image.LANCZOS)


def tiles_of(image, cells: int, threshold: int):
    """Cut into 8x8 tiles, one bit a pixel, brighter than threshold is set."""
    grid = []
    for row in range(cells):
        line = []
        for column in range(cells):
            tile = []
            for y in range(8):
                bits = 0
                for x in range(8):
                    pixel = image.getpixel((column * 8 + x, row * 8 + y))
                    if pixel > threshold:
                        bits |= 0x80 >> x
                tile.append(bits)
            line.append(tuple(tile))
        grid.append(line)
    return grid


def main() -> int:
    cells = int(sys.argv[1]) if len(sys.argv) > 1 else 12
    threshold = int(sys.argv[2]) if len(sys.argv) > 2 else 96

    image = rasterise(cells * 8)
    grid = tiles_of(image, cells, threshold)

    blank = tuple([0] * 8)
    shapes = []
    codes = []
    for line in grid:
        row_codes = []
        for tile in line:
            if tile == blank:
                row_codes.append(0x20)          # a space is a space
                continue
            if tile not in shapes:
                shapes.append(tile)
            row_codes.append(FIRST_CODE + shapes.index(tile))
        codes.append(row_codes)

    print(f"{cells}x{cells} characters, {len(shapes)} of them distinct "
          f"(room for {MAX_TILES})")
    if len(shapes) > MAX_TILES:
        print("too many - try a smaller size", file=sys.stderr)
        return 1

    with OUT.open("w") as f:
        f.write(f"""/*
 * The PokerTH logo, as characters. Generated by make-logo.py from
 * pokerth.svg - do not edit; run the script again instead.
 *
 * {cells} by {cells} characters, {len(shapes)} of them distinct: the tiles that
 * repeat are stored once and the blank ones are spaces. They live at code
 * {FIRST_CODE} upwards, which is only free while the TED is told not to invert
 * the upper half of the character set.
 */
#define LOGO_CELLS {cells}
#define LOGO_FIRST_CODE {FIRST_CODE}
#define LOGO_SHAPES {len(shapes)}

static const unsigned char LOGO_SHAPE[LOGO_SHAPES][8] = {{
""")
        for tile in shapes:
            f.write("    { " + ", ".join(f"0x{b:02X}" for b in tile) + " },\n")
        f.write("};\n\nstatic const unsigned char LOGO_MAP[LOGO_CELLS][LOGO_CELLS] = {\n")
        for row_codes in codes:
            f.write("    { " + ", ".join(str(c) for c in row_codes) + " },\n")
        f.write("};\n")
    print(f"wrote {OUT.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
